### ISSUE TITLE
Pair issue

### ISSUE THREAD

**Issue by ghost** [PiMaker/Teletun#2]
When i select the contact i have this messege:
Connected! Sending Invitation!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "teletun.py", line 83, in main_loop_starter
    receiver.message(main_loop())
  File "/usr/local/lib/python2.7/dist-packages/pytg/utils.py", line 29, in start
    cr = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytg/receiver.py", line 212, in message
    function.send(message)
  File "teletun.py", line 101, in main_loop
    data = base64.b64decode(msg.text)
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

I was try in Ubuntu 16.04.4 LTS and Debian 9.4.
I want to use this code because in my plan i have unlimited Telegram :D

**Comment by DopeforHope** [comment]
Just comment line 128 `sender.msg(username, unicode('Hello, I would like to establish a Layer 3 Tunnel with you! -teletun'))`.
One side tries to decode it as base64 and therefore raises the exception.

**Comment by cofob** [comment]
Close the issue
